### PR TITLE
test deploy on one VM

### PR DESCRIPTION
**Pull request by ra312**
On branch k8s-on-gcp
 Changes to be committed:
	modified:   env.sh
	modified:   ../management/Makefile
	modified:   ../management/env.sh

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubeflow/gcp-blueprints/pull/339/checks?check_run_id=4544604427

**Comment by ra312** [comment]
Hi @Arhell,
I just read these messages! Thanks a lot for reviewing! I will fix the conflict and merge at the earliest possible time.
Kind regards, @ra312

**Comment by ra312** [comment]
I came across this PR again. It would be nice to merge, thanks for help.
> Please sign CLA https://github.com/kubeflow/gcp-blueprints/pull/339/checks?check_run_id=4544604427

Here is the CLA
image

**Comment by zijianjoy** [comment]
Hello @ra312 I need some help understanding the purpose of this PR, can you tell me more what it is about and why it is beneficial?

**Pull request closed without merging**
